### ISSUE TITLE
Option to disable table of contents

### ISSUE THREAD

**Issue by brennerm** [lesjoursfr/html-to-epub#147]
Hey :), thanks for building this!

My use case is to convert single web pages into and epub file so the ToC usually only contains one entry which makes it a bit pointless. I'd like to see an option that disables the ToC completely. Is that something you think would be feasible to implement? If so, I'll be happy to contribute that feature.

**Comment by e-adrien** [comment]
Hey.

I don't mind adding an option to do that but the generated file won't be valid anymore.
If I understand the EPUB specification, the file has to contain a navigation element.

[2.1   Package Conformance](https://www.w3.org/submissions/epub-packages/#sec-package-conformance)
![image](https://github.com/user-attachments/assets/6864d13f-42c9-4e22-88bf-644474072d5a)

If we do this I think it will be nice to name this option like `generateInvalidEpubWithoutToc` (or something similar) to avoid confusion.

**Comment by brennerm** [comment]
Good to know! After your comment I did some research. Apparently to achieve what I'd like to have, all that is necessary is to remove the ToC entry from the spine object in the content.opf file.

This way the ToC is still part of the ebook and you can still access it using your reader's ToC feature, but it won't be visible simply when scrolling through the book.

My suggestion would be to introduce two new options, something like `hideCover` and `hideToc`, which allow to exclude the cover and the ToC from the spine but still include them in the ebook archive.

Let me know what you think. [Here's an example ebook](https://paste.c-net.org/MephestoPaved) where I commented out the cover and ToC entries in the spines which produces the desired outcome.

**Comment by vhrita** [comment]
I need that too, created a script that automatic sends newsletters every mornings to my kindle. I'll appreciate if the brenner's suggestion could be implemented, the hideCover will work well for me.

**Comment by e-adrien** [comment]
Hey. I just published a [new version](https://github.com/lesjoursfr/html-to-epub/releases/tag/4.4.0). 🙂 
You can now hide the ToC by setting the `hideToc` option to `true`.
If you want to hide the cover you can just unset the `cover` option.

**Comment by brennerm** [comment]
@e-adrien Awesome, thank you! Will give it a try and provide an update. :+1:

**Comment by brennerm** [comment]
@e-adrien Works flawlessly! From my point of view this issue can be closed.

**Comment by e-adrien** [comment]
Thank you for the issue and the feedback. 🙂
